[API_KEYS]
# API key for AvScanner service
avScanner = 77a1b44dc96bae47ecb8ac2f42449c5ee237ccab6e8cc2f35b3dec1cc6b5b913

# API key for AbuseIPDB service

[SETTINGS]
# Alert threshold for log analysis
threshold = 5

